<?php
include '../../conn.php';

if(isset($_POST['save'])){

    $CATG_CODE = $_POST['CATG_CODE'];
    $CATG_NAME = $_POST['CATG_NAME'];
    $CATG_ASSET_MAIN_ACNT_CODE = $_POST['CATG_ASSET_MAIN_ACNT_CODE'];
    $CATG_ASSET_SUB_ACNT_CODE = $_POST['CATG_ASSET_SUB_ACNT_CODE'];
    $CATG_FUND_MAIN_ACNT_CODE = $_POST['CATG_FUND_MAIN_ACNT_CODE'];
    $CATG_FUND_SUB_ACNT_CODE = $_POST['CATG_FUND_SUB_ACNT_CODE'];
    $CATG_DEPRN_MAIN_ACNT_CODE = $_POST['CATG_DEPRN_MAIN_ACNT_CODE'];
    $CATG_DEPRN_SUB_ACNT_CODE = $_POST['CATG_DEPRN_SUB_ACNT_CODE'];
    $CATG_PL_MAIN_ACNT_CODE = $_POST['CATG_PL_MAIN_ACNT_CODE'];
    $CATG_PL_SUB_ACNT_CODE = $_POST['CATG_PL_SUB_ACNT_CODE'];
    $CATG_MIN_AMT = $_POST['CATG_MIN_AMT'];
    $CATG_MAX_AMT = $_POST['CATG_MAX_AMT'];
    $CATG_FLOOR_VALUE = $_POST['CATG_FLOOR_VALUE'];
    $CATG_STD_DEPRN = $_POST['CATG_STD_DEPRN'];
    $CATG_FLOOR_PER_VAL = $_POST['CATG_FLOOR_PER_VAL'];

    $q = oci_parse($conn, " UPDATE FIX_CATEGORY SET CATG_ASSET_MAIN_ACNT_CODE = '".$CATG_ASSET_MAIN_ACNT_CODE."', CATG_ASSET_SUB_ACNT_CODE = '".$CATG_ASSET_SUB_ACNT_CODE."',
    CATG_FUND_MAIN_ACNT_CODE = '".$CATG_FUND_MAIN_ACNT_CODE."', CATG_FUND_SUB_ACNT_CODE = '".$CATG_FUND_SUB_ACNT_CODE."', CATG_DEPRN_MAIN_ACNT_CODE = '".$CATG_DEPRN_MAIN_ACNT_CODE."',
    CATG_DEPRN_SUB_ACNT_CODE  = '".$CATG_DEPRN_SUB_ACNT_CODE."', CATG_PL_MAIN_ACNT_CODE = '".$CATG_PL_MAIN_ACNT_CODE."', CATG_PL_SUB_ACNT_CODE = '".$CATG_PL_SUB_ACNT_CODE."',
    CATG_MIN_AMT = ".$CATG_MIN_AMT.", CATG_MAX_AMT = ".$CATG_MAX_AMT.", CATG_FLOOR_VALUE = ".$CATG_FLOOR_VALUE.",
    CATG_STD_DEPRN = ".$CATG_STD_DEPRN.", CATG_FLOOR_PER_VAL = '".$CATG_FLOOR_PER_VAL."' WHERE CATG_CODE = '".$CATG_CODE."'");

    $r = oci_execute($q);

    if ($r){
        echo "<script type='text/javascript'>alert('DATA UPDATE SUCCESSFULLY !');document.location='page-cat-asset.php'</script>";
    } else {
        echo "<script type='text/javascript'>alert('ERROR !');document.location='page-cat-edit.php'</script>";
    }
}
?>